apiVersion: v1
kind: Pod
metadata:
  name: gcloudutils
spec:
  containers:
  - name: gcloudutils
    image: google/cloud-sdk:latest
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        cpu: 250m
        memory: 1Gi
      requests:
        cpu: 100m
        memory: 1Gi
  restartPolicy: Always
  serviceAccount: {{ .Values.serviceAccount }}

