apiVersion: v1
kind: Pod
metadata:
  labels:
    app.kubernetes.io/component: repo-server
    app.kubernetes.io/instance: argocd
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: argocd-repo-server
    app.kubernetes.io/part-of: argocd
    app.kubernetes.io/version: v2.2.5-2
    helm.sh/chart: argo-cd-4.1.0
    pod-template-hash: 649ff88f9c
  name: argocd-repo-server
  namespace: argocd
spec:
  containers:
  - command: [ "tail", "-f", "/dev/null" ]
    env:
    - name: HELM_CACHE_HOME
      value: /helm-working-dir
    - name: HELM_CONFIG_HOME
      value: /helm-working-dir
    - name: HELM_DATA_HOME
      value: /helm-working-dir
    image: docker.io/cmaahs/argocd-sops-gcp:v2.2.5-2
    name: repo-server
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  serviceAccountName: argocd-repo-server
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
