steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', '${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}:${_TAG}', 'cloudBuildPublishGAR/docker/argocd/.' ]
images:
- '${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}:${_TAG}'
substitutions:
  _LOCATION: us
  _REPOSITORY: docker
  _IMAGE: argocd-cmaahs
  _TAG: 2.3.1-1
