#!/usr/bin/env zsh

gcloud projects add-iam-policy-binding maahsome-shared \
    --member "serviceAccount:tf-gke-staging-private-rh95@maahsome-staging.iam.gserviceaccount.com" \
    --role "roles/cloudkms.cryptoKeyEncrypterDecrypter"

gcloud iam service-accounts add-iam-policy-binding tf-gke-staging-private-rh95@maahsome-staging.iam.gserviceaccount.com \
    --role roles/iam.workloadIdentityUser \
    --member "serviceAccount:maahsome-staging.svc.id.goog[argocd/argocd-repo-server]"


